language: node_js
dist: trusty
os: linux

env:
  global:
    - PROJECT_NAME="jenkins_slave" TEST_TAG="$PROJECT_NAME:test" GOSS_VERSION="v0.3.9"

services:
  - docker

stages:
  - syntax
  - build
  - test

jobs:
  include:
  - stage: syntax
    name: Dockerfile syntax
    install:
      - npm install -g dockerlint
    script: dockerlint -f Dockerfile
  - stage: build
    name: Build docker image
    script:
      - docker build --tag "${TEST_TAG}" .
  - stage: test
    name: Test docker image
    install:
      - docker build --tag "${TEST_TAG}" .
      - curl -L https://goss.rocks/install | sudo sh
      - curl -L https://raw.githubusercontent.com/aelsabbahy/goss/"${GOSS_VERSION}"/extras/dgoss/dgoss > dgoss
      - chmod +rx dgoss
      - sudo mv dgoss /usr/local/bin
    script: dgoss run "${TEST_TAG}"